name: Run Tests


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    # PostgresSQL
    services:
      postgres:
        # Docker image
        image: postgres
        # Environment variables
        env:
          POSTGRES_NAME: ${{ secrets.POSTGRES_NAME }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
        # Ports
        ports:
          - ${{ secrets.DB_PORT }}:5432
        # Options for PostgresSQL
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      # Install Python
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6
      # Update pip and install all requirements
      - name: Install Deps
        working-directory: .
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # Run tests with setting variables in .env file
      - name: Run tests
        working-directory: .
        run: |
          touch .env   
          
          echo SECRET_KEY='${{ secrets.SECRET_KEY }}' >> .env
          echo DEBUG='${{ secrets.DEBUG }}' >> .env
          echo ALLOWED_HOSTS='${{ secrets.ALLOWED_HOSTS }}' >> .env
        
          echo ACCOUNT_ALLOW_REGISTRATION='${{ secrets.ACCOUNT_ALLOW_REGISTRATION }}' >> .env
          
          echo EMAIL_BACKEND='${{ secrets.EMAIL_BACKEND }}' >> .env
          echo EMAIL_HOST='${{ secrets.EMAIL_HOST }}' >> .env
          echo EMAIL_PORT='${{ secrets.EMAIL_PORT }}' >> .env
          echo EMAIL_HOST_USER='${{ secrets.EMAIL_HOST_USER }}' >> .env
          echo EMAIL_HOST_PASSWORD='${{ secrets.EMAIL_HOST_PASSWORD }}' >> .env
          echo EMAIL_USE_TLS='${{ secrets.EMAIL_USE_TLS }}' >> .env
          echo EMAIL_USE_SSL='${{ secrets.EMAIL_USE_SSL }}' >> .env
          
          echo POSTGRES_NAME='${{ secrets.POSTGRES_NAME }}' >> .env
          echo POSTGRES_USER='${{ secrets.POSTGRES_USER }}' >> .env
          echo POSTGRES_PASSWORD='${{ secrets.POSTGRES_PASSWORD }}' >> .env
          echo DB_HOST='${{ secrets.DB_HOST }}' >> .env
          echo DB_PORT='${{ secrets.DB_PORT }}' >> .env
          
          echo CLOUDINARY_NAME='${{ secrets.CLOUDINARY_NAME }}' >> .env
          echo CLOUDINARY_API_KEY='${{ secrets.CLOUDINARY_API_KEY }}' >> .env
          echo CLOUDINARY_API_SECRET='${{ secrets.CLOUDINARY_API_SECRET }}' >> .env
        
          cat .env
          
          pytest
